CREATE TABLE TB_HEROS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    POWER TEXT NOT NULL
)

--create
INSERT INTO TB_HEROS (NAME, POWER)
VALUES
    ('Flash', 'Speed'),
    ('Aquaman', 'Water'),
    ('Batman', 'Money')

--read
SELECT * FROM TB_HEROS;
SELECT * FROM TB_HEROS WHERE NAME = 'Flash';

--update
UPDATE TB_HEROS
SET NAME = 'Goku', POWER = 'God'
WHERE ID = 1;

--delete
DELETE FROM TB_HEROS WHERE ID =2;